kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: testapp
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      nodePort: 80
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: testapp
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: NodePort